/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'slate-gray': 'var(--bg-elevated)',
        'deep-charcoal': 'var(--bg-base)',
        'electric-blue': '#007AFF',
        'royal-purple': '#8E44AD',
        'vivid-orange': '#F59E0B',
        'crimson-red': '#EF4444',
        'emerald-green': '#10B981',
        'on-tertiary-fixed': '#111c2d',
        'surface-bright': 'var(--bg-surface)',
        'outline-variant': 'var(--border)',
        'surface-variant': 'var(--bg-hover)',
        'on-surface-variant': 'var(--text-secondary)',
        'on-primary-fixed': '#001a42',
        'inverse-on-surface': '#233143',
        'tertiary-container': '#8691a7',
        'error': 'var(--accent-red)',
        'surface-container-lowest': 'var(--bg-base)',
        'tertiary-fixed-dim': '#bcc7de',
        'on-background': 'var(--text-primary)',
        'on-primary-fixed-variant': '#004395',
        'on-surface': 'var(--text-primary)',
        'primary-fixed-dim': 'var(--accent)',
        'primary': 'var(--accent)',
        'surface-container-high': 'var(--bg-active)',
        'on-tertiary': '#263143',
        'secondary': 'var(--text-secondary)',
        'border-subtle': 'var(--border)',
        'secondary-fixed': '#dae2fd',
        'tertiary-fixed': '#d8e3fb',
        'error-container': '#93000a',
        'surface-dim': 'var(--bg-surface)',
        'primary-fixed': '#d8e2ff',
        'on-secondary-container': 'var(--text-secondary)',
        'warning': 'var(--accent-orange)',
        'surface-container-low': 'var(--bg-elevated)',
        'inverse-primary': '#005ac2',
        'secondary-fixed-dim': 'var(--text-secondary)',
        'surface-tint': 'var(--accent)',
        'background': 'var(--bg-surface)',
        'on-primary': '#002e6a',
        'surface': 'var(--bg-surface)',
        'primary-container': 'var(--accent-hover)',
        'surface-container-highest': 'var(--bg-hover)',
        'surface-container': 'var(--bg-elevated)',
        'on-error': '#690005',
        'on-tertiary-container': '#1f2a3c',
        'on-primary-container': '#00285d',
        'tertiary': '#bcc7de',
        'surface-deep': 'var(--bg-base)',
        'secondary-container': '#3f465c',
        'success': 'var(--accent-green)',
        'outline': 'var(--text-muted)',
        'on-secondary-fixed-variant': '#3f465c',
        'on-tertiary-fixed-variant': '#3c475a',
        'inverse-surface': 'var(--text-primary)',
        'on-secondary-fixed': '#131b2e',
        'on-error-container': '#ffdad6',
        'on-secondary': '#283044'
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem'
      },
      spacing: {
        'stack-sm': '0.5rem',
        'stack-lg': '2rem',
        'section-padding': '2.5rem',
        'container-max': '1440px',
        'sidebar-width': '260px',
        'gutter': '1.5rem',
        'stack-md': '1rem'
      },
      fontFamily: {
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'table-header': ['Inter', 'sans-serif'],
        'display-kpi': ['Inter', 'sans-serif'],
        'mono-data': ['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif']
      },
      fontSize: {
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'table-header': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'display-kpi': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'mono-data': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }]
      }
    },
  },
  plugins: [],
};